/* oxlint-disable nextjs/no-html-link-for-pages -- Full document navigation supports both static Vercel routes and Vinext. */
import Image from 'next/image';
import {links} from '@/lib/profile';
import styles from './BiographyPage.module.css';

export default function BiographyPage(){
 return <main className={styles.page}>
  <nav className={styles.nav} aria-label="Điều hướng hồ sơ"><a href="/">← Trang chủ</a><a href="#ket-noi">Kết nối với thầy</a></nav>
  <header className={styles.header}>
   <div><p className={styles.eyebrow}>GIANG HA · BISC · 9LEARNING</p><h1>Hà Long Giang</h1><p className={styles.lead}>Founder BISC &amp; 9Learning<br/>Quản trị doanh nghiệp · Tài chính · Giáo dục</p><p>Hà Long Giang, với tên giao tiếp Giang Ha, là chuyên gia trong lĩnh vực quản trị doanh nghiệp, kiểm soát nội bộ, quản lý rủi ro, tài chính doanh nghiệp, M&amp;A và phát triển bền vững (ESG).</p></div>
   <Image className={styles.portrait} unoptimized src="/model-evidence/approved-front.png" width={404} height={1065} alt="Minh họa hoạt hình Hà Long Giang mặc áo polo trắng, cầm sổ xanh"/>
  </header>
  <div className={styles.content}>
   <section id="bisc-9learning"><h2>Hà Long Giang với BISC và 9Learning</h2><p>Là Founder BISC và 9Learning, thầy kết nối kinh nghiệm chuyên môn với hoạt động đào tạo. Tại BISC, thầy giảng dạy các chương trình kế toán, kiểm toán quốc tế, trong đó có ACCA và ICAEW. Tại 9Learning, thầy tham gia đào tạo ứng dụng AI trong tài chính, kế toán và kiểm toán.</p><p>Trọng tâm của hoạt động giảng dạy là giúp người học hiểu kiến thức chuyên ngành và liên hệ với bối cảnh công việc. Kinh nghiệm làm việc cùng doanh nghiệp thuộc nhiều lĩnh vực tạo nền tảng cho những phân tích và góc nhìn thực tiễn trong quá trình chia sẻ với học viên.</p><div className={styles.links}><a href="https://bisc.edu.vn/">Tìm hiểu BISC ↗</a><a href="https://9learning.edu.vn/">Tìm hiểu 9Learning ↗</a></div></section>
   <section id="acca-icaew"><h2>Giang Ha ACCA và hành trình chuyên môn</h2><p>Thầy Hà Long Giang là hội viên kỳ cựu của Hiệp hội Kế toán Công chứng Anh quốc ACCA (FCCA) và hội viên ICAEW Chartered Accountant (ICAEW ACA). Hồ sơ giảng viên tại BISC giới thiệu thầy với các danh vị FCCA, ACA và BFP.</p><p>Hành trình chinh phục danh vị ICAEW Chartered Accountant của thầy được Báo Dân trí ghi nhận, thể hiện tinh thần học hỏi và theo đuổi các chuẩn mực nghề nghiệp quốc tế. Kinh nghiệm giảng dạy ACCA và ICAEW đi cùng cam kết nâng cao năng lực trong tài chính, kế toán và quản trị doanh nghiệp.</p><div className={styles.links}><a href={links.article}>Đọc bài viết về hành trình ICAEW trên Dân trí ↗</a><a href="https://bisc.edu.vn/chuong-trinh-acca/cap-do-applied-skills/audit-and-assurance-aa_129.html">Hồ sơ giảng viên ACCA tại BISC ↗</a></div></section>
   <section id="ca-singapore"><h2>Singapore Chartered Accountant – CA (Singapore)</h2><p>Trong bài chia sẻ trên trang Facebook cá nhân, Hà Long Giang (Giang Ha) thông báo đã trở thành Singapore Chartered Accountant – CA (Singapore) thông qua chương trình chuyển đổi dành cho hội viên ACCA của Viện Kế toán Công chứng Singapore (ISCA).</p><p>Thầy nhìn nhận danh vị này là sự ghi nhận cho hành trình làm nghề và là động lực tiếp tục học hỏi, phát triển năng lực theo chuẩn mực quốc tế.</p><div className={styles.links}><a href={links.singapore}>Đọc chia sẻ của thầy về CA (Singapore) ↗</a></div></section>
   <section id="quan-tri"><h2>Quản trị, kiểm soát nội bộ và quản lý rủi ro</h2><p>Trong hoạt động chuyên môn, thầy đã tham gia xây dựng và hoàn thiện các hệ thống quản trị, kiểm soát nội bộ và quản lý rủi ro. Mục tiêu là nâng cao hiệu quả vận hành, tính minh bạch và khả năng tăng trưởng dài hạn của tổ chức.</p><p>Góc nhìn quản trị gắn với cách doanh nghiệp vận hành, ra quyết định và kiểm soát các rủi ro trong thực tế. Những chia sẻ của thầy hướng đến việc củng cố nền tảng quản trị để tổ chức thích ứng với môi trường kinh doanh thay đổi.</p></section>
   <section id="tai-chinh-esg"><h2>Tài chính doanh nghiệp, M&amp;A và ESG</h2><p>Những phân tích của thầy về tài chính doanh nghiệp và hoạt động mua bán, sáp nhập (M&amp;A) góp phần hỗ trợ các tổ chức nâng cao năng lực cạnh tranh và tối ưu hóa giá trị sau đầu tư.</p><p>Bên cạnh đó, thầy quan tâm đến việc thúc đẩy thông lệ quản trị hiện đại và tích hợp các tiêu chuẩn môi trường, xã hội và quản trị (ESG) vào chiến lược phát triển doanh nghiệp. Đây là một phần trong định hướng xây dựng nền tảng phát triển bền vững, gắn hiệu quả hoạt động với tầm nhìn dài hạn.</p></section>
   <section id="ket-noi"><h2>Kết nối với Hà Long Giang</h2><p>Theo dõi các chia sẻ về học tập, nghề nghiệp và chuyên môn của thầy qua những kênh dưới đây. Thông tin chương trình đào tạo được cập nhật trên website BISC và 9Learning.</p><div className={styles.links}><a href={links.facebook} rel="me">Facebook Hà Long Giang ↗</a><a href={links.tiktok} rel="me">TikTok @halonggiangg ↗</a><a href="/">Khám phá hồ sơ tương tác →</a></div></section>
  </div>
 </main>;
}
